COMMAND_LEFT = 'LEFT'
COMMAND_RIGHT = 'RIGHT'
COMMAND_UP = 'UP'
COMMAND_DOWN = 'DOWN'
COMMAND_FORWARD = 'FORWARD'
COMMAND_BACKWARD = 'BACKWARD'

VALID_COMMANDS = {COMMAND_LEFT,COMMAND_RIGHT,COMMAND_UP,COMMAND_DOWN,COMMAND_FORWARD,COMMAND_BACKWARD}